--Creating dimension tables then inserting the data
--DIM_CATEGORY
CREATE TABLE DIM_CATEGORY (
    CATEGORY_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    CATEGORY_NAME VARCHAR2(100),
    CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (CATEGORY_KEY)
);

INSERT INTO DIM_CATEGORY (CATEGORY_NAME)
SELECT DISTINCT ServiceCategory
FROM stg_tickets;

COMMIT;

CREATE TABLE DIM_AGENT (
    AGENT_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    AGENT_NAME VARCHAR2(100),
    CONSTRAINT PK_DIM_AGENT PRIMARY KEY (AGENT_KEY)
);

--DIM_AGENT
INSERT INTO DIM_AGENT (AGENT_NAME)
SELECT DISTINCT ASSIGNEDTO
FROM stg_tickets;

COMMIT;

SELECT * FROM DIM_AGENT
FETCH FIRST 20 ROWS ONLY;

--DIM_DEPARTMENT
CREATE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    DEPARTMENT_NAME VARCHAR2(100),
    CONSTRAINT PK_DIM_DEPARTMENT PRIMARY KEY (DEPARTMENT_KEY)
);

INSERT INTO DIM_DEPARTMENT (DEPARTMENT_NAME)
SELECT DISTINCT DEPARTMENT
FROM STG_TICKETS;

COMMIT;

--DIM_PRIORITY
CREATE TABLE DIM_PRIORITY (
    PRIORITY_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    PRIORITY_NAME VARCHAR2(20),
    CONSTRAINT PK_DIM_PRIORITY PRIMARY KEY (PRIORITY_KEY)
);

INSERT INTO DIM_PRIORITY (PRIORITY_NAME)
SELECT DISTINCT PriorityLevel 
FROM STG_TICKETS;

COMMIT;

--DIM_STATUS
CREATE TABLE DIM_STATUS (
    STATUS_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    STATUS_NAME VARCHAR2(50),
    CONSTRAINT PK_DIM_STATUS PRIMARY KEY (STATUS_KEY)
);

INSERT INTO DIM_STATUS (STATUS_NAME)
SELECT DISTINCT STATUS
FROM STG_TICKETS;

COMMIT;

--DIM_IMPACT
CREATE TABLE DIM_IMPACT (
    IMPACT_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
    IMPACT_NAME VARCHAR2(20),
    CONSTRAINT PK_DIM_IMPACT PRIMARY KEY (IMPACT_KEY)
);


INSERT INTO DIM_IMPACT (IMPACT_NAME)
SELECT DISTINCT ImpactLevel 
FROM STG_TICKETS;

COMMIT;

--Creating Date Dimension
CREATE TABLE DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH_NUMBER NUMBER,
    MONTH_NAME VARCHAR2(20),
    DAY_NUMBER NUMBER,
    DAY_NAME VARCHAR2(20)
);

--Populating dates from 2024–2027

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(dt,'YYYYMMDD')),
    dt,
    EXTRACT(YEAR FROM dt),
    TO_NUMBER(TO_CHAR(dt,'Q')),
    EXTRACT(MONTH FROM dt),
    TO_CHAR(dt,'Month'),
    EXTRACT(DAY FROM dt),
    TO_CHAR(dt,'Day')
FROM (
    SELECT DATE '2024-01-01' + LEVEL - 1 dt
    FROM dual
    CONNECT BY LEVEL <= 1461
);

COMMIT;
--Adding a "Not Closed Yet" row to DIM_DATE so as to use CLOSE_DATE_KEY = 0 for open tickets.
INSERT INTO DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    YEAR,
    QUARTER,
    MONTH_NUMBER,
    MONTH_NAME,
    DAY_NUMBER,
    DAY_NAME
)
VALUES
(
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    'Not Closed',
    NULL,
    NULL
);

COMMIT;


























