--Total Tickets by Department
SELECT 
    d.DEPARTMENT_NAME,
    COUNT(f.TICKET_ID) AS TOTAL_TICKETS
FROM FACT_TICKETS f
JOIN DIM_DEPARTMENT d
    ON f.DEPARTMENT_KEY = d.DEPARTMENT_KEY
GROUP BY d.DEPARTMENT_NAME
ORDER BY TOTAL_TICKETS DESC;

--SLA Compliance Rate
SELECT 
    ROUND(
        100.0 * SUM(CASE WHEN SLA_BREACHED = 0 THEN 1 ELSE 0 END) 
        / COUNT(*), 
    1) AS SLA_COMPLIANCE_PERCENT
FROM FACT_TICKETS;

--Tickets by Priority
SELECT 
    p.PRIORITY_NAME,
    COUNT(f.TICKET_ID) AS TOTAL_TICKETS
FROM FACT_TICKETS f
JOIN DIM_PRIORITY p
    ON f.PRIORITY_KEY = p.PRIORITY_KEY
GROUP BY p.PRIORITY_NAME
ORDER BY TOTAL_TICKETS DESC;

--Average Resolution Time by Category
SELECT 
    c.CATEGORY_NAME,
    ROUND(AVG(f.RESOLUTION_HOURS),2) AS AVG_RESOLUTION_TIME
FROM FACT_TICKETS f
JOIN DIM_CATEGORY c
    ON f.CATEGORY_KEY = c.CATEGORY_KEY
GROUP BY c.CATEGORY_NAME
ORDER BY AVG_RESOLUTION_TIME DESC;


--SLA Breach by Category
SELECT 
    c.CATEGORY_NAME,
    COUNT(*) AS SLA_BREACHES
FROM FACT_TICKETS f
JOIN DIM_CATEGORY c
    ON f.CATEGORY_KEY = c.CATEGORY_KEY
WHERE f.SLA_BREACHED = 1
GROUP BY c.CATEGORY_NAME
ORDER BY SLA_BREACHES DESC;


--Average Customer Satisfaction by Agent
SELECT 
    a.AGENT_NAME,
    ROUND(AVG(f.USER_FEEDBACK_RATING),2) AS AVG_CSAT
FROM FACT_TICKETS f
JOIN DIM_AGENT a
    ON f.AGENT_KEY = a.AGENT_KEY
GROUP BY a.AGENT_NAME
ORDER BY AVG_CSAT DESC;

--Open vs Closed Tickets
SELECT 
    STATUS,
    COUNT(TicketID) AS TOTAL_TICKETS
FROM STG_TICKETS
GROUP BY STATUS;




